development:
  adapter: async

test:
  adapter: async

production:
  adapter: postgresql
  url: postgres://mvgqbdpjlhymdm:5fb33de744ce03512ae422b8532fd6faa683fb7986270480c2c544917c7743f2@ec2-54-247-81-76.eu-west-1.compute.amazonaws.com:5432/doh21sopvbh0h

